### ISSUE TITLE
Sympol ①  not converted in the pdf file

### ISSUE THREAD

**Issue by andrew97s** [aspose-words/Aspose.Words-for-Java#110]
hi :
  i use the aspose to convert word file into pdf file (linux), and found out that the sympol ① not converted , but then i try it with windows , it converted just fine. so if there is a way to make it work in linux too ？

![the sympol in word file](https://github.com/user-attachments/assets/b69c961c-f8ca-4e96-acf2-c19504cdaeee)

![the sympol in pdf file with linux](https://github.com/user-attachments/assets/6613ec89-60ec-4012-ba9e-9002f33efb3b)
[Uploading abnormalSympol.docx…]()

![the sympol in pdf file with windows](https://github.com/user-attachments/assets/e96e1e91-85b2-4d33-8887-8ef3ec46ff4f)

**Comment by AlexNosk** [comment]
@andrew97s Most likely, the problem occurs because the font used for rendering the problematic glyphs is not not available in the environment where the document is converted to PDF. If Aspose.Words cannot find the fonts used in the document the [fonts are substituted](https://docs.aspose.com/words/java/manipulate-and-substitute-truetype-fonts/). This might lead into the layout differences due to differences in fonts metrics. You can implement [IWarningCallback ](https://reference.aspose.com/words/java/com.aspose.words/iwarningcallback/)to get a notification when font substitution is performed.
The following articles can be useful for you:
<https://docs.aspose.com/words/java/specify-truetype-fonts-location/>
<https://docs.aspose.com/words/java/install-truetype-fonts-on-linux/>

if after installing the required fonts the problem still persist. Please attach your input and output documents here for our reference, Unfortunately, screenshots does not allow to analyze the issue. 

PS: The main place for getting support is [Aspose.Words support forum](https://forum.aspose.com/c/words/8).

**Comment by andrew97s** [comment]
i use the IWarningCallback to found that some fonts didn't exists in linux enviroment, and i install it , things worked out !  
thanks !
