### ISSUE TITLE
Getting only 198 Rows and 198 Cells in MS Word Table by using aspose word library in JAVA

### ISSUE THREAD

**Issue by kp144** [aspose-words/Aspose.Words-for-Java#35]
`int totalRow = doc.getChildNodes(NodeType.ROW, true).getCount();`
`System.out.println("Total Row : " + totalRow);`

Getting 198 Rows but i  have more then 198 rows in MS Word Table

**OR**

`int totalCellMethod = doc.getChildNodes(NodeType.CELL, true).getCount();`
`System.out.println("Total CELL : " + totalCellMethod);`

Getting 198 Cells but i  have more CELL in MS Word Table

**Comment by kp144** [comment]
@saqibmasood Sir may you looking into this...

**Comment by sohail-aspose** [comment]
@kp144 
Thanks for your patience. There is a limitation on table size in trial version of Aspose.Words for Java, you can only read 40 rows and 198 cells of a table at max. In order to read tables of larger size, you need to have a valid license.

You can either get a temporary license at http://www.aspose.com/corporate/purchase/temporary-license.aspx if you are still evaluating Aspose.Words or purchase a license from http://www.aspose.com/purchase/default.aspx

Please feel free to reach us if you need further assistance.

**Comment by kp144** [comment]
Okay.. is there any updated JAR which is used to get more then 198 CELLS without any Licence

**Comment by sohail-aspose** [comment]
Unfortunately not, you need to buy a license if you want to read tables of larger size (more than 40 rows and 198 cells).
