### ISSUE TITLE
doc convert to html math pic error

### ISSUE THREAD

**Issue by alexlis** [aspose-words/Aspose.Words-for-Java#65]

**Comment by AlexNosk** [comment]
@alexlis Could you please attach your input document for testing? We will check the issue and provide you more information.

**Comment by alexlis** [comment]
ok,thanks!
you can download from [http://47.105.64.144/html/123.docx](url)

**Comment by alexlis** [comment]
> @alexlis Could you please attach your input document for testing? We will check the issue and provide you more information.

I try all the latest java version，they all have such problems。

**Comment by AlexNosk** [comment]
@alexlis Thank you for additional information. I investigated the problem and managed to reproduce it. The reason of the problem is lack of fonts on your side. The formula is a metafile, that is rendered to PNG upon conversion to HTML. Symbol font is used in the metafile and if this font is not present Aspose.Words tries to find an alternative font, if there is no suitable alternative you see tofu symbol.

**Comment by alexlis** [comment]
> @alexlis Thank you for additional information. I investigated the problem and managed to reproduce it. The reason of the problem is lack of fonts on your side. The formula is a metafile, that is rendered to PNG upon conversion to HTML. Symbol font is used in the metafile and if this font is not present Aspose.Words tries to find an alternative font, if there is no suitable alternative you see tofu symbol.

Thank you very much.
