### ISSUE TITLE
Word to PDF paragraph style is messy

### ISSUE THREAD

**Issue by dhp888666** [aspose-words/Aspose.Words-for-Java#67]
Word to PDF paragraph style will be messy, will not be able to put automatic line feed, resulting in the entire document format chaos

**Comment by AlexNosk** [comment]
@dhp888666 Could you please attach your input and output documents here for testing? We will check the issue and provide you more information.

**Comment by dhp888666** [comment]
> @ dhp888666您能否在此处附加您的输入和输出文档以进行测试？我们将检查问题并为您提供更多信息。

How to set paragraph style Chinese board style, according to Chinese custom control first character and allow punctuation overflow boundary

**Comment by dhp888666** [comment]
> @ dhp888666您能否在此处附加您的输入和输出文档以进行测试？我们将检查问题并为您提供更多信息。
[testPdf.pdf](https://github.com/aspose-words/Aspose.Words-for-Java/files/5193359/testPdf.pdf)
[testWord.docx](https://github.com/aspose-words/Aspose.Words-for-Java/files/5193361/testWord.docx)

**Comment by AlexNosk** [comment]
@dhp888666 Thank you for additional information. The difference you mentioned might be caused by difference in fonts. Please make sure the fonts used in the document are installed on the system where conversion is performed. If the fonts are available, but the problem still persists, please attach the fonts here for further investigation. 
You can implement IWarningCallback to check whether fonts in your document are replaced with alternative fonts. See the code below:
```java
Document doc = new Document("C:\\Temp\\in.docx");
doc.setWarningCallback(new WarningCallback());
doc.save("C:\\Temp\\out.pdf");
```

```java
import com.aspose.words.IWarningCallback;
import com.aspose.words.WarningInfo;

public class WarningCallback implements IWarningCallback {
    @Override
    public void warning(WarningInfo warningInfo) {
        System.out.println(warningInfo.getDescription());
        System.out.println("=============================================");
    }
}
```

**Comment by AlexNosk** [comment]
@dhp888666 Do you still have the above mentioned issue? Or can the request be considered as resolved?
